const tintColorLight = '#8A2BE2';
const tintColorDark = '#A45EE5';

export default {
  light: {
    text: '#000000',
    background: '#FFFFFF',
    tint: tintColorLight,
    tabIconDefault: '#CCCCCC',
    tabIconSelected: tintColorLight,
    codeBackground: '#F6F8FA',
    codeBorder: '#E1E4E8',
    codeText: '#24292E',
    cardBackground: '#FFFFFF',
    buttonBackground: '#FFFFFF',
    buttonIcon: '#333333',
    iconBackground: '#EEEEEE',
    modalBackground: '#FFFFFF',
    modalOverlay: 'rgba(0, 0, 0, 0.5)',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    separator: '#EEEEEE',
    buttonGradientStart: '#8A2BE2',
    buttonGradientEnd: '#9370DB',
  },
  dark: {
    text: '#FFFFFF',
    background: '#121212',
    tint: tintColorDark,
    tabIconDefault: '#666666',
    tabIconSelected: tintColorDark,
    codeBackground: '#1E1E1E',
    codeBorder: '#333333',
    codeText: '#E8E8E8',
    cardBackground: '#1E1E1E',
    buttonBackground: '#333333',
    buttonIcon: '#FFFFFF',
    iconBackground: '#333333',
    modalBackground: '#242424',
    modalOverlay: 'rgba(0, 0, 0, 0.7)',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    separator: '#333333',
    buttonGradientStart: '#8A2BE2',
    buttonGradientEnd: '#9370DB',
  },
};